# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GRPCServerBase.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GRPCServerBase.proto',
  package='GRPC',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14GRPCServerBase.proto\x12\x04GRPC\"\x1b\n\x0bGrpcRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\",\n\tGrpcReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\x32x\n\x04gRPC\x12\x33\n\x0bGrpcConnect\x12\x11.GRPC.GrpcRequest\x1a\x0f.GRPC.GrpcReply\"\x00\x12;\n\x11GrpcConnectStream\x12\x11.GRPC.GrpcRequest\x1a\x0f.GRPC.GrpcReply\"\x00\x30\x01\x62\x06proto3')
)




_GRPCREQUEST = _descriptor.Descriptor(
  name='GrpcRequest',
  full_name='GRPC.GrpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GRPC.GrpcRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=57,
)


_GRPCREPLY = _descriptor.Descriptor(
  name='GrpcReply',
  full_name='GRPC.GrpcReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='GRPC.GrpcReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='GRPC.GrpcReply.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['GrpcRequest'] = _GRPCREQUEST
DESCRIPTOR.message_types_by_name['GrpcReply'] = _GRPCREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrpcRequest = _reflection.GeneratedProtocolMessageType('GrpcRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRPCREQUEST,
  '__module__' : 'GRPCServerBase_pb2'
  # @@protoc_insertion_point(class_scope:GRPC.GrpcRequest)
  })
_sym_db.RegisterMessage(GrpcRequest)

GrpcReply = _reflection.GeneratedProtocolMessageType('GrpcReply', (_message.Message,), {
  'DESCRIPTOR' : _GRPCREPLY,
  '__module__' : 'GRPCServerBase_pb2'
  # @@protoc_insertion_point(class_scope:GRPC.GrpcReply)
  })
_sym_db.RegisterMessage(GrpcReply)



_GRPC = _descriptor.ServiceDescriptor(
  name='gRPC',
  full_name='GRPC.gRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=105,
  serialized_end=225,
  methods=[
  _descriptor.MethodDescriptor(
    name='GrpcConnect',
    full_name='GRPC.gRPC.GrpcConnect',
    index=0,
    containing_service=None,
    input_type=_GRPCREQUEST,
    output_type=_GRPCREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GrpcConnectStream',
    full_name='GRPC.gRPC.GrpcConnectStream',
    index=1,
    containing_service=None,
    input_type=_GRPCREQUEST,
    output_type=_GRPCREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPC)

DESCRIPTOR.services_by_name['gRPC'] = _GRPC

# @@protoc_insertion_point(module_scope)
